### ISSUE TITLE
csgo_server_restarter.sp

### ISSUE THREAD

**Issue by spot88** [splewis/sm-misc#1]
Will this work on Windows servers?
Atm. im running a "loop" .bat script, so if the server crash and closes it's starts up again. 
And to catch a update, i have reboot every night.

**Comment by splewis** [comment]
I've used it on linux and windows servers before. I think whether it works depends on how the server is launched, though. 

You could test just by seeing what the "_restart" command (either from rcon or the server directly) does (since that's all the plugin does).

**Comment by spot88** [comment]
It actually work, it just shut down the windows, and by script starts again.

**Comment by splewis** [comment]
Yes. https://github.com/splewis/sm-misc/blob/master/scripting/csgo_server_restarter.sp#L84

Note that is requires the SteamWorks extension to be installed to detect being out-of-date.
